#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Generator script for backtest_integrated_v3.py"""
import os

out = open(r'D:\Qclaw_Trading\backtest_integrated_v3.py', 'w', encoding='utf-8')

lines = [
    '#!/usr/bin/env python3',
    '# -*- coding: utf-8 -*-',
    'import sys, os, json, glob, statistics, time',
    'from datetime import datetime as dt',
    'from collections import defaultdict',
    'HISTORY_DIR = r"D:\\Qclaw_Trading\\data\\history_long_v2"',
    'POOL_FILE = r"D:\\Qclaw_Trading\\data\\etf_pool_V1_full.json"',
    'OUTPUT_DIR = r"D:\\Qclaw_Trading\\review"',
    'DEF_MAX_DEV, DEF_TOP_N, DEF_LB = 15.0, 3, 3',
    'DEF_ATR_F = 0.85',
    'DEF_SC_W1, DEF_SC_W3, DEF_SC_W8 = 0.40, 0.40, 0.20',
    "C_BONUS, DEF_CAPITAL = 0.02, 100000.0",
    '',
    'def load_all_data():',
    '    with open(POOL_FILE, encoding="utf-8") as f: pool = json.load(f)',
    '    etfs = pool if isinstance(pool, list) else pool.get("data", [])',
    '    series, ohlc, code_cat, avail_weeks = {}, {}, {}, set()',
    '    for etf in etfs:',
    '        code, cat = etf["code"], etf.get("category", "") or ""',
    '        code_cat[code] = cat',
    '        matches = glob.glob(os.path.join(HISTORY_DIR, code + ".json"))',
    '        if not matches: matches = glob.glob(os.path.join(HISTORY_DIR, "*" + code + ".json"))',
    '        if not matches: continue',
    '        try:',
    '            with open(matches[0], encoding="utf-8") as f: raw = f.read().replace("NaN", "null")',
    '            d = json.loads(raw)',
    '            recs = d.get("records", []) if isinstance(d, dict) else d',
    '            if not recs: continue',
    '            if isinstance(recs[0], list):',
    '                recs = [{"date": r[0], "open": r[1], "high": r[2], "low": r[3], "close": r[4], "vol": r[5]} for r in recs]',
    '            elif "w" in recs[0]:',
    '                recs = [{"date": r.get("date", ""), "open": r.get("open", r.get("close", 0)), "high": r.get("high", r.get("close", 0)), "low": r.get("low", r.get("close", 0)), "close": r.get("close", 0), "vol": r.get("vol", 0)} for r in recs]',
    '            weeks = {}',
    '            for r in recs:',
    '                ds = r.get("date", "") or r.get("w", "")',
    '                if not ds: continue',
    '                try:',
    '                    y, wn, _ = dt.strptime(ds, "%Y-%m-%d").isocalendar()',
    '                    wk = "{}-W{:02d}".format(y, wn)',
    '                    if wk not in weeks or ds > weeks[wk][0]:',
    '                        weeks[wk] = (ds, r.get("close", 0), r.get("open", 0), r.get("high", 0), r.get("low", 0), r.get("vol", 0))',
    '                except: pass',
    '            if not weeks: continue',
    '            srt = sorted(weeks.items())',
    '            series[code] = [(wk, v[1]) for wk, v in srt]',
    '            ohlc[code] = {wk: {"o": v[2], "h": v[3], "l": v[4], "c": v[1], "v": v[5]} for wk, v in srt}',
    '            avail_weeks.update(w for w, _ in srt)',
    '        except: continue',
    '    all_weeks = sorted(avail_weeks)',
    '    atr = {}',
    '    for code, wd in ohlc.items():',
    '        if len(wd) < 30: continue',
    '        wk_list = sorted(wd.keys()); trs = [None] * len(wk_list)',
    '        for i in range(1, len(wk_list)):',
    '            cur, prv = wd[wk_list[i]], wd[wk_list[i-1]]',
    '            trs[i] = max(cur["h"] - cur["l"], abs(cur["h"] - prv["c"]), abs(cur["l"] - prv["c"]))',
    '        atrs = {}',
    '        for i in range(21, len(wk_list)):',
    '            vals = [trs[j] for j in range(i-20, i+1) if trs[j] is not None]',
    '            if len(vals) >= 21:',
    '                fast = sum(vals[-14:]) / 14; slow = sum(vals) / 21',
    '                if slow > 0: atrs[wk_list[i]] = fast / slow',
    '        atr[code] = atrs',
    '    return etfs, series, ohlc, code_cat, all_weeks, atr',
    '',
    'def calc_factors(code, wk_list, idx, series, ohlc, atr, vol_div_n=None):',
    '    ohlc_c = ohlc.get(code, {}); srt = series.get(code, [])',
    '    res = {"vol_ratio": None, "c_pat": False, "vol_divergence": False, "ksft": None}',
    '    if idx < 21 or idx >= len(srt): return res',
    '    price = srt[idx][1]',
    '    if not price or price <= 0: return res',
    '    ma5 = sum(srt[j][1] for j in range(idx-4, idx+1)) / 5',
    '    ma21 = sum(srt[j][1] for j in range(idx-20, idx+1)) / 21',
    '    if ma21 == 0: return res',
    '    dev = abs(price / ma21 - 1) * 100',
    '    if dev > DEF_MAX_DEV: return res',
    '    sig_week = srt[idx][0]',
    '    ar = atr.get(code, {}).get(sig_week)',
    '    if ar is not None and ar < DEF_ATR_F: return res',
    '    mom = price / srt[idx-DEF_LB][1] - 1',
    '    mom1w = price / srt[idx-1][1] - 1 if idx >= 1 else mom',
    '    mom8w = price / srt[idx-8][1] - 1 if idx >= 8 else mom',
    '    score = DEF_SC_W1 * mom1w + DEF_SC_W3 * mom + DEF_SC_W8 * mom8w',
    '    res["score"] = score; res["dev"] = dev',
    '    w0 = ohlc_c.get(sig_week, {})',
    '    if w0 and all(w0.get(k) is not None for k in ("c", "o", "h", "l")):',
    '        ci, oi, hi, li = w0["c"], w0["o"], w0["h"], w0["l"]',
    '        body = abs(ci - oi); u_shadow = hi - max(ci, oi)',
    '        l_shadow = min(ci, oi) - li; s2b = u_shadow / body if body > 0 else 99',
    '        vol_vals = [ohlc_c.get(wk_list[j], {}).get("v", 0) for j in range(max(0, idx-9), idx+1)]',
    '        vol_vals = [v for v in vol_vals if v and v > 0]',
    '        avg_v10 = sum(vol_vals) / len(vol_vals) if vol_vals else 1',
    '        vol_r = w0.get("v", 0) / avg_v10 if avg_v10 > 0 else 1',
    '        g20 = 0',
    '        if idx >= 20:',
    '            pc = ohlc_c.get(wk_list[idx-20], {}).get("c")',
    '            if pc and pc > 0: g20 = ci / pc - 1',
    '        res["c_pat"] = (ci > oi and s2b > 1.0 and l_shadow < body * 0.5',
    '                        and vol_r < 1.5 and ci > ma5 > ma21 and g20 < 0.5)',
    '        res["vol_ratio"] = vol_r',
    '        # KSFT: weekly close position in 5-day range',
    '        day_closes = [ohlc_c.get(wk_list[j], {}).get("c", 0) for j in range(idx-4, idx+1)]',
    '        day_closes = [c for c in day_closes if c > 0]',
    '        if day_closes:',
    '            lo5 = min(day_closes); hi5 = max(day_closes)',
    '            if hi5 > lo5: res["ksft"] = (ci - lo5) / (hi5 - lo5)',
    '        if vol_div_n and idx >= vol_div_n:',
    '            prices_s = [srt[j][1] for j in range(idx-vol_div_n+1, idx+1) if srt[j][1] and srt[j][1] > 0]',
    '            is_ph = (ci >= max(prices_s)) if prices_s else False',
    '            vols_n = [ohlc_c.get(wk_list[j], {}).get("v", 0) for j in range(idx-vol_div_n+1, idx+1)]',
    '            vols_n = [v for v in vols_n if v and v > 0]',
    '            is_vh = (w0.get("v", 0) >= max(vols_n) * 0.95) if vols_n else False',
    '            res["vol_divergence"] = is_ph and not is_vh',
    '    return res',
    '',
    'def run_oos(etfs, series, ohlc, code_cat, all_weeks, atr, is_end_idx, oos_end_idx,',
    '             enable_vol_div=False, vol_div_n=4, atr_w="equal", use_ksft=False, ksft_bonus=0.0):',
    '    code_wklist = {c: [wk for wk, _ in s] for c, s in series.items()}',
    '    first_idx = {}',
    '    for code, s in series.items():',
    '        for j, (wk, _) in enumerate(s):',
    '            if wk == all_weeks[is_end_idx]: first_idx[code] = j; break',
    '    portfolio = {}; cash = DEF_CAPITAL; eq_curve = []; n_buys = n_sells = 0',
    '    for si in range(is_end_idx, oos_end_idx):',
    '        sig_week = all_weeks[si]; exec_week = all_weeks[si + 1]',
    '        candidates = []',
    '        for code, s in series.items():',
    '            fi = first_idx.get(code)',
    '            if fi is None: continue',
    '            idx = fi + (si - is_end_idx)',
    '            if idx < 21 or idx >= len(s): continue',
    '            f = calc_factors(code, code_wklist.get(code, []), idx, series, ohlc, atr,',
    '                             vol_div_n if enable_vol_div else None)',
    '            if "score" not in f: continue',
    '            if enable_vol_div and f.get("vol_divergence"): continue',
    '            adj = f["score"]',
    '            if f.get("c_pat"): adj += C_BONUS',
    '            if use_ksft and f.get("ksft") is not None:',
    '                adj += ksft_bonus * (f["ksft"] - 0.5)',
    '            candidates.append({"code": code, "close": s[idx][1], "_adj": adj, "cat": code_cat.get(code, ""),"ksft": f.get("ksft")})',
    '        candidates.sort(key=lambda x: x["_adj"], reverse=True)',
    '        cats = set(); target = []',
    '        for c in candidates:',
    '            if c["cat"] not in cats: cats.add(c["cat"]); target.append(c)',
    '        target = target[:DEF_TOP_N]; target_codes = {t["code"] for t in target}',
    '        for code in portfolio:',
    '            p = next((cl for wk, cl in series[code] if wk == sig_week), None)',
    '            if p and p > portfolio[code]["hwm"]: portfolio[code]["hwm"] = p',
    '        to_sell = []',
    '        for code, pos in list(portfolio.items()):',
    '            p = next((cl for wk, cl in series[code] if wk == sig_week), None)',
    '            if p is None: to_sell.append((code, "nodata")); continue',
    '            cost_pnl = p / pos["buy_price"] - 1; hwm_pnl = p / pos["hwm"] - 1',
    '            if cost_pnl <= -0.08 or hwm_pnl <= -0.10: to_sell.append((code, "stop"))',
    '            elif code not in target_codes: to_sell.append((code, "rebalance"))',
    '        for code, _ in to_sell:',
    '            pos = portfolio.pop(code)',
    '            p = next((cl for wk, cl in series[code] if wk == sig_week), None)',
    '            cash += pos["weight"] * (p or pos["buy_price"]); n_sells += 1',
    '        slots = DEF_TOP_N - len(portfolio)',
    '        if slots > 0 and cash > 0:',
    '            buy_list = [t for t in target if t["code"] not in portfolio]',
    '            total_assets = cash + sum(pos["weight"] * pos["buy_price"] for pos in portfolio.values())',
    '            buy_weights = []',
    '            for bc in buy_list[:slots]:',
    '                p_exec = next((cl for wk, cl in series[bc["code"]] if wk == sig_week), None)',
    '                if p_exec is None or p_exec <= 0: continue',
    '                w_atr = atr.get(bc["code"], {}).get(sig_week, 1)',
    '                w_atr = max(w_atr, 0.3)',
    '                if atr_w == "inv_atr": rw = 1.0 / w_atr',
    '                elif atr_w == "inv_sqrt_atr": rw = 1.0 / (w_atr ** 0.5)',
    '                else: rw = 1.0',
    '                buy_weights.append((bc["code"], p_exec, rw))',
    '            if buy_weights:',
    '                total_w = sum(w for _, _, w in buy_weights)',
    '                for code, p_exec, rw in buy_weights:',
    '                    slot_val = total_assets * (rw / total_w)',
    '                    weight = slot_val / p_exec; cost = weight * p_exec',
    '                    if cost > cash * 0.98: weight = cash * 0.98 / p_exec; cost = weight * p_exec',
    '                    if weight <= 0: continue',
    '                    cash -= cost; portfolio[code] = {"weight": weight, "buy_price": p_exec, "hwm": p_exec}; n_buys += 1',
    '        equity = cash + sum(',
    '            pos["weight"] * next((cl for wk, cl in series[c] if wk == exec_week), pos["buy_price"])',
    '            for c, pos in portfolio.items())',
    '        eq_curve.append({"w": exec_week, "eq": equity})',
    '    eqs = [e["eq"] for e in eq_curve]; n = len(eqs)',
    '    if n < 2: return None',
    '    init, final = eqs[0], eqs[-1]',
    '    total_ret = (final / init - 1) * 100; years = n / 52',
    '    ann_ret = ((final / init) ** (1 / years) - 1) * 100 if years > 0 else 0',
    '    peak = eqs[0]; max_dd = 0',
    '    for eq in eqs:',
    '        if eq > peak: peak = eq; dd = eq / peak - 1',
    '        if dd < max_dd: max_dd = dd',
    '    w_rets = [eqs[i] / eqs[i-1] - 1 for i in range(1, n) if eqs[i-1] > 0]',
    '    if w_rets:',
    '        avg_w = statistics.mean(w_rets); std_w = statistics.stdev(w_rets) if len(w_rets) > 1 else 1e-9',
    '        sharpe = (avg_w * 52 - 0.02) / (std_w * 52 ** 0.5) if std_w > 0 else 0',
    '        win_rate = sum(1 for r in w_rets if r > 0) / len(w_rets) * 100',
    '    else: sharpe = win_rate = 0',
    '    return {"ann_ret": ann_ret, "total_ret": total_ret, "max_dd": max_dd * 100,',
    '            "sharpe": sharpe, "win_rate": win_rate, "n_buys": n_buys, "n_sells": n_sells, "n_weeks": n}',
    '',
    'def main():',
    '    print("\\n" + "=" * 70)',
    '    print("  BACKTEST v3 - VolDiv + ATRdyn + KSFT")',
    '    print("=" * 70)',
    '    t0 = time.time(); print("\\n[Data] Loading...")',
    '    etfs, series, ohlc, code_cat, all_weeks, atr = load_all_data()',
    '    print("    {} ETFs, {} weeks ({} - {})".format(len(series), len(all_weeks), all_weeks[0], all_weeks[-1]))',
    '    is_start = max(0, next((i for i, w in enumerate(all_weeks) if w == "2017-W01"), 0) - 1)',
    '    is_end = next((i for i, w in enumerate(all_weeks) if w == "2023-W01"), 0)',
    '    oos_end = len(all_weeks) - 1',
    '    print("  IS: {} - {} ({} wks)".format(all_weeks[is_start], all_weeks[is_end-1], is_end - is_start))',
    '    print("  OOS: {} - {} ({} wks)".format(all_weeks[is_end], all_weeks[oos_end-1], oos_end - is_end))',
    '',
    '    # Configs: (label, enable_vol_div, atr_w, vol_div_n, use_ksft, ksft_bonus)',
    '    configs = [',
    '        ("Baseline(C+0.02)",            False, "equal",    0, False, 0.0),',
    '        ("+VD=4(VolDiv)",               True,  "equal",    4, False, 0.0),',
    '        ("+VD=5(VolDiv)",               True,  "equal",    5, False, 0.0),',
    '        ("+InvATR",                      False, "inv_atr",   0, False, 0.0),',
    '        ("+InvSqrtATR",                  False, "inv_sqrt_atr", 0, False, 0.0),',
    '        ("+VD=4+InvATR",                 True,  "inv_atr",   4, False, 0.0),',
    '        ("+KSFT(0.001)",                 False, "equal",    0, True,  0.001),',
    '        ("+KSFT(0.002)",                 False, "equal",    0, True,  0.002),',
    '        ("+VD=4+KSFT(0.001)",            True,  "equal",    4, True,  0.001),',
    '    ]',
    '',
    '    sep70 = "#" * 70',
    '    print("\\n" + sep70 + "\\n  # IS (2017 - 2022)\\n" + sep70)',
    '    is_results = []',
    '    for label, evd, eaw, vdn, uks, kbf in configs:',
    '        print("  {:30s}".format(label), end="", flush=True)',
    '        r = run_oos(etfs, series, ohlc, code_cat, all_weeks, atr, is_start, is_end,',
    '                    evd, vdn, eaw, uks, kbf)',
    '        if r:',
    '            is_results.append((label, evd, eaw, vdn, uks, kbf, r))',
    '            best_s = max(x[-1]["sharpe"] for x in is_results)',
    '            tag = " *" if r["sharpe"] == best_s else ""',
    '            print("  Ann={:+.2f}%  DD={:6.1f}%  Sharpe={:.3f}{}".format(r["ann_ret"], r["max_dd"], r["sharpe"], tag))',
    '    if not is_results: print("No IS results!"); return',
    '    best_idx = max(range(len(is_results)), key=lambda i: is_results[i][-1]["sharpe"])',
    '    best_is = is_results[best_idx][-1]',
    '    print("\\n  IS Best({}): Ann={:+.2f}% Sharpe={:.3f} DD={:.1f}%".format(',
    '          is_results[best_idx][0], best_is["ann_ret"], best_is["sharpe"], best_is["max_dd"]))',
    '',
    '    print("\\n" + sep70 + "\\n  # OOS (2023 - 2026)\\n" + sep70)',
    '    oos_results = []',
    '    for label, evd, eaw, vdn, uks, kbf, _ in is_results:',
    '        print("  {:30s}".format(label), end="", flush=True)',
    '        r = run_oos(etfs, series, ohlc, code_cat, all_weeks, atr, is_end, oos_end,',
    '                    evd, vdn, eaw, uks, kbf)',
    '        if r:',
    '            oos_results.append((label, r))',
    '            print("  Ann={:+.2f}%  DD={:6.1f}%  Sharpe={:.3f}".format(r["ann_ret"], r["max_dd"], r["sharpe"]))',
    '',
    '    sep110 = "=" * 110',
    '    print("\\n" + sep110)',
    '    print("  {:35s}  {:>8}  {:>8}  {:>7}  {:>8}  {:>8}  {:>7}".format(',
    '          "Config", "IS Ann", "IS Shp", "IS-DD", "OOS Ann", "OOS Shp", "OOS-DD"))',
    '    print("  " + "-" * 110)',
    '    for i, (label, is_r) in enumerate([(x[0], x[-1]) for x in is_results]):',
    '        oos_r = oos_results[i][1]; star = " *" if i == best_idx else ""',
    '        print("  {:35s}  {:>+8.2f}%  {:8.3f}  {:6.1f}%  {:>+8.2f}%  {:8.3f}  {:6.1f}%{}".format(',
    '              label, is_r["ann_ret"], is_r["sharpe"], is_r["max_dd"],',
    '              oos_r["ann_ret"], oos_r["sharpe"], oos_r["max_dd"], star))',
    '',
    '    ts = time.strftime("%Y%m%d_%H%M%S")',
    '    out_file = os.path.join(OUTPUT_DIR, "backtest_v3_{}.json".format(ts))',
    '    os.makedirs(OUTPUT_DIR, exist_ok=True)',
    '    with open(out_file, "w", encoding="utf-8") as f:',
    '        json.dump({"is_results": [(x[0], x[-1]) for x in is_results],',
    '                   "oos_results": oos_results, "best_idx": best_idx},',
    '                   f, ensure_ascii=False, indent=2)',
    '    print("\\nSaved: " + out_file)',
    '    print("Time: {:.0f}s".format(time.time() - t0))',
    '',
    'if __name__ == "__main__": main()',
]

for line in lines:
    out.write(line + "\n")
out.close()
print("backtest_integrated_v3.py written OK")
